spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

